<configuration>
  <property>
    <name>dfs.journalnode.rpc-address</name>
    <value>0.0.0.0:41100</value>
  </property>
  <property>
    <name>dfs.namenode.kerberos.internal.spnego.principal</name>
    <value>HTTP/hadoop@XIAOMI.HADOOP</value>
  </property>
  <property>
    <name>dfs.client.failover.proxy.provider.xiaomitst-lpc</name>
    <value>org.apache.hadoop.hdfs.server.namenode.ha.ConfiguredFailoverProxyProvider</value>
  </property>
  <property>
    <name>dfs.datanode.kerberos.principal</name>
    <value>hdfs/hadoop@XIAOMI.HADOOP</value>
  </property>
  <property>
    <name>dfs.block.access.token.enable</name>
    <value>true</value>
  </property>
  <property>
    <name>dfs.datanode.data.dir</name>
    <value>/home/hadoop/hdd/hdfs/xiaomitst-lpc/datanode/41600</value>
  </property>
  <property>
    <name>dfs.namenode.name.dir</name>
    <value>/home/hadoop/hdd/hdfs/xiaomitst-lpc/namenode/41200</value>
  </property>
  <property>
    <name>ignore.secure.ports.for.testing</name>
    <value>true</value>
  </property>
  <property>
    <name>dfs.journalnode.kerberos.principal</name>
    <value>hdfs/hadoop@XIAOMI.HADOOP</value>
  </property>
  <property>
    <name>dfs.namenode.safemode.threshold-pct</name>
    <value>0.99f</value>
  </property>
  <property>
    <name>dfs.block.size</name>
    <value>128m</value>
  </property>
  <property>
    <name>dfs.namenode.shared.edits.dir</name>
    <value>qjournal://10.235.114.37:41100;10.235.114.38:41100;10.235.114.39:41100/xiaomitst-lpc</value>
  </property>
  <property>
    <name>dfs.datanode.balance.bandwidthPerSec</name>
    <value>20971520</value>
  </property>
  <property>
    <name>net.topology.table.file.name</name>
    <value>/home/hadoop/app/hdfs/xiaomitst-lpc/namenode/41200/rackinfo.txt</value>
  </property>
  <property>
    <name>dfs.namenode.keytab.file</name>
    <value>/etc/hadoop/conf/hdfs.keytab</value>
  </property>
  <property>
    <name>dfs.namenode.kerberos.principal</name>
    <value>hdfs/hadoop@XIAOMI.HADOOP</value>
  </property>
  <property>
    <name>fs.trash.interval</name>
    <value>10080</value>
  </property>
  <property>
    <name>dfs.datanode.synconclose</name>
    <value>true</value>
  </property>
  <property>
    <name>dfs.ha.automatic-failover.enabled</name>
    <value>true</value>
  </property>
  <property>
    <name>dfs.metrics.percentiles.intervals</name>
    <value>60,300,900</value>
  </property>
  <property>
    <name>dfs.journalnode.edits.dir</name>
    <value>/home/hadoop/hdd/hdfs/xiaomitst-lpc/journalnode/41100</value>
  </property>
  <property>
    <name>dfs.secondary.namenode.kerberos.internal.spnego.principal</name>
    <value>HTTP/hadoop@XIAOMI.HADOOP</value>
  </property>
  <property>
    <name>dfs.webhdfs.enabled</name>
    <value>True</value>
  </property>
  <property>
    <name>dfs.namenode.handler.count</name>
    <value>64</value>
  </property>
  <property>
    <name>dfs.client.slow.log.threshold.ms</name>
    <value>10000</value>
  </property>
  <property>
    <name>fs.permissions.umask-mode</name>
    <value>022</value>
  </property>
  <property>
    <name>dfs.datanode.http.address</name>
    <value>0.0.0.0:41601</value>
  </property>
  <property>
    <name>dfs.datanode.socket.write.timeout</name>
    <value>60000</value>
  </property>
  <property>
    <name>dfs.datanode.failed.volumes.tolerated</name>
    <value>0</value>
  </property>
  <property>
    <name>dfs.ha.fencing.ssh.private-key-files</name>
    <value>/home/work/.ssh/id_rsa</value>
  </property>
  <property>
    <name>dfs.nameservices</name>
    <value>xiaomitst-lpc</value>
  </property>
  <property>
    <name>dfs.datanode.address</name>
    <value>0.0.0.0:41602</value>
  </property>
  <property>
    <name>dfs.ha.namenodes.xiaomitst-lpc</name>
    <value>host0,host1</value>
  </property>
  <property>
    <name>hadoop.security.group.mapping</name>
    <value>org.apache.hadoop.security.ConfigurationBasedGroupsMapping</value>
  </property>
  <property>
    <name>dfs.namenode.upgrade.permission</name>
    <value>0777</value>
  </property>
  <property>
    <name>dfs.datanode.max.xcievers</name>
    <value>4096</value>
  </property>
  <property>
    <name>dfs.block.local-path-access.user</name>
    <value>work, hbase, hbase_srv, hbase_tst, hbase_prc, impala</value>
  </property>
  <property>
    <name>dfs.permissions</name>
    <value>false</value>
  </property>
  <property>
    <name>dfs.web.authentication.kerberos.keytab</name>
    <value>/etc/hadoop/conf/hdfs.keytab</value>
  </property>
  <property>
    <name>dfs.client.read.shortcircuit</name>
    <value>true</value>
  </property>
  <property>
    <name>dfs.client.read.shortcircuit.skip.auth</name>
    <value>true</value>
  </property>
  <property>
    <name>dfs.ha.fencing.methods</name>
    <value>sshfence&#xA;shell(/bin/true)</value>
  </property>
  <property>
    <name>fs.trash.checkpoint.interval</name>
    <value>1440</value>
  </property>
  <property>
    <name>dfs.journalnode.keytab.file</name>
    <value>/etc/hadoop/conf/hdfs.keytab</value>
  </property>
  <property>
    <name>dfs.namenode.rpc-address.xiaomitst-lpc.host0</name>
    <value>10.235.114.37:41200</value>
  </property>
  <property>
    <name>hadoop.security.group.mapping.file.name</name>
    <value>/home/hadoop/app/hdfs/xiaomitst-lpc/namenode/41200/hadoop-groups.conf</value>
  </property>
  <property>
    <name>dfs.ha.fencing.ssh.connect-timeout</name>
    <value>2000</value>
  </property>
  <property>
    <name>dfs.namenode.rpc-address.xiaomitst-lpc.host1</name>
    <value>10.235.114.38:41200</value>
  </property>
  <property>
    <name>dfs.secondary.namenode.keytab.file</name>
    <value>/etc/hadoop/conf/hdfs.keytab</value>
  </property>
  <property>
    <name>dfs.web.authentication.kerberos.principal</name>
    <value>HTTP/hadoop@XIAOMI.HADOOP</value>
  </property>
  <property>
    <name>dfs.datanode.ipc.address</name>
    <value>0.0.0.0:41600</value>
  </property>
  <property>
    <name>dfs.web.ugi</name>
    <value>hdfs,supergroup</value>
  </property>
  <property>
    <name>dfs.ha.zkfc.port</name>
    <value>41500</value>
  </property>
  <property>
    <name>dfs.namenode.http-address.xiaomitst-lpc.host0</name>
    <value>10.235.114.37:41201</value>
  </property>
  <property>
    <name>dfs.hosts.exclude</name>
    <value>/home/hadoop/app/hdfs/xiaomitst-lpc/namenode/41200/excludes</value>
  </property>
  <property>
    <name>dfs.secondary.namenode.kerberos.principal</name>
    <value>hdfs/hadoop@XIAOMI.HADOOP</value>
  </property>
  <property>
    <name>dfs.datanode.keytab.file</name>
    <value>/etc/hadoop/conf/hdfs.keytab</value>
  </property>
  <property>
    <name>net.topology.node.switch.mapping.impl</name>
    <value>org.apache.hadoop.net.TableMapping</value>
  </property>
  <property>
    <name>dfs.permissions.superusergroup</name>
    <value>supergroup</value>
  </property>
  <property>
    <name>dfs.journalnode.http-address</name>
    <value>0.0.0.0:41101</value>
  </property>
  <property>
    <name>dfs.journalnode.kerberos.internal.spnego.principal</name>
    <value>HTTP/hadoop@XIAOMI.HADOOP</value>
  </property>
  <property>
    <name>dfs.namenode.replication.min</name>
    <value>1</value>
  </property>
  <property>
    <name>dfs.domain.socket.path</name>
    <value>/home/hadoop/app/hdfs/xiaomitst-lpc/datanode/41600/dn_socket</value>
  </property>
  <property>
    <name>dfs.permissions.superuser</name>
    <value>hdfs_admin</value>
  </property>
  <property>
    <name>dfs.client.socket-timeout</name>
    <value>60000</value>
  </property>
  <property>
    <name>dfs.datanode.sync.behind.writes</name>
    <value>true</value>
  </property>
  <property>
    <name>dfs.datanode.data.dir.perm</name>
    <value>700</value>
  </property>
  <property>
    <name>dfs.namenode.http-address.xiaomitst-lpc.host1</name>
    <value>10.235.114.38:41201</value>
  </property>
  <property>
    <name>dfs.cluster.administrators</name>
    <value>hdfs_admin</value>
  </property>
</configuration>
